port: 7890
socks-port: 7891
mixed-port: 7893
tproxy-port: 7895
routing-mark: 5237
allow-lan: true
bind-address: "*"
ipv6: false
find-process-mode: strict
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
unified-delay: true
tcp-concurrent: true
profile:
  tracing: true
  store-selected: true
  store-fake-ip: true
geodata-mode: true
geodata-loader: standard
geo-auto-update: false
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country-lite.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"
dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*.lan'
    - "+.local"
    - "localhost.ptlogin2.qq.com"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "localhost.sec.qq.com"
    - "localhost.work.weixin.qq.com"
    - "localhost.weixin.qq.com"
  default-nameserver:
    - 114.114.114.114
    - 114.114.115.115
    - 223.5.5.5
    - 119.29.29.29
    - 1.1.1.1
    - 8.8.8.8
  nameserver-policy:
    'www.baidu.com': '114.114.114.114'
    '+.internal.crop.com': '10.0.0.1'
    'geosite:cn,private':
    - 114.114.114.114
    - 114.114.115.115
    'geosite:geolocation-!cn':
    - tls://1dot1dot1dot1.cloudflare-dns.com
    - tls://8.8.4.4
    - https://1.1.1.1/dns-query
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
tun:
  enable: true
  stack: system
  device: mihomo
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
